sudo: required
dist: trusty
language: c++
compiler:
  - arm-none-eabi-g++
cache:
  directories:
    - "${HOME}/persist"

before_script:
# Extra gcc versions
  # For teensy build
  - sudo apt-get install gcc-arm-none-eabi
  - pwd
script:
  - $CC -I/home/travis/build/hristoandreev/MB1502-raspberry-pi/wiringPi/wiringPi main.c -o spi_synth -lwiringPi -lcrypt -lm -lrt
after_failure:
